# Generated by Django 5.2.8 on 2025-12-08 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cost_price_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='animal_type',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Goat', 'Goat'), ('Sheep', 'Sheep'), ('Pig', 'Pig'), ('Chicken', 'Chicken')], default='Cow', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='meat_type',
            field=models.CharField(choices=[('Whole', 'Whole'), ('Beef', 'Beef'), ('Mutton', 'Mutton'), ('Goat Meat', 'Goat Meat'), ('Pork', 'Pork'), ('Chicken', 'Chicken')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
