# Generated by Django 5.2.8 on 2025-12-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
