# Generated by Django 5.2.8 on 2025-12-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cost_price_product_purchase_price_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='purchase',
            new_name='purchase_order',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
